# 线上配置文件
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
server:
  port: 8101
spring:
  session:
    timeout: 25920000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.223.66.160:3306/yubi
    username: root
    password: 123456
  redis:
    database: 0
    host: 124.223.66.160
    port: 6379
    timeout: 5000
  rabbitmq:
    host: 124.223.66.160
    port: 5672
    password: guest
    username: guest
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.yupi.springbootinit.controller
yuapi:
  client:
    access-key: 4m79lq55p3qczulz8hcc2ra2p1g3grlc
    secret-key: haeybkoxigaq8j7gh7t83dzqdmoa2dbs